const test = require('node:test');
const assert = require('node:assert/strict');
const C = require('../app/src/main/assets/core.js');
function fixture() {
  const state=C.fresh();state.classes=[{id:'a',name:'수학반',days:[1,2,3,4,5],time:'16:00',color:'#8974C9',archived:false},{id:'b',name:'영어반',days:[6],time:'11:00',color:'#529E99',archived:false}];
  state.students=[{id:'s1',name:'김하늘',classId:'a',memo:'',phone:'',contactId:'',guardians:[],active:true,joinedDate:'2026-10-01',archivedDate:null},{id:'s2',name:'박지우',classId:'b',memo:'',phone:'',contactId:'',guardians:[],active:true,joinedDate:'2026-10-01',archivedDate:null}];return state;
}
const now=new Date('2026-10-08T16:17:00');
test('local date boundaries and invalid dates',()=>{assert.equal(C.validDate('2026-02-30'),false);assert.equal(C.validDate('2024-02-29'),true);assert.equal(C.shiftDate('2026-12-31',1),'2027-01-01');assert.equal(C.localDate(new Date(2026,0,1,0,5)),'2026-01-01');});
test('weekday and enrollment filters keep unchecked separate from absence',()=>{const s=fixture();assert.equal(C.roster(s,'2026-10-08').length,1);assert.equal(C.roster(s,'2026-10-08','all',false).length,2);assert.equal(C.roster(s,'2026-09-30').length,0);const t=C.count(C.roster(s,'2026-10-08'));assert.equal(t.unmarked,1);assert.equal(t.absent,0);});
test('mark is immutable; edits replace without duplicate; reset removes record',()=>{const s=fixture(),a=C.mark(s,'s1','2026-10-08','present',undefined,now);assert.equal(s.records.length,0);assert.equal(a.records[0].time,'16:17');const b=C.mark(a,'s1','2026-10-08','late','병원',now);assert.equal(b.records.length,1);assert.equal(b.records[0].status,'late');assert.equal(b.records[0].note,'병원');assert.equal(C.mark(b,'s1','2026-10-08','unmarked',undefined,now).records.length,0);});
test('backdated status does not invent attendance time; future writes rejected',()=>{assert.equal(C.mark(fixture(),'s1','2026-10-07','present','',now).records[0].time,'');assert.throws(()=>C.mark(fixture(),'s1','2026-10-09','present','',now));assert.throws(()=>C.mark(fixture(),'s1','2026-09-30','present','',now));});
test('attendance snapshots survive renaming, changing class and archiving',()=>{let s=C.mark(fixture(),'s1','2026-10-08','present','',now);s.students[0].name='이름 변경';s.students[0].classId='b';s.classes[0].name='반 변경';s.students[0].active=false;s.students[0].archivedDate='2026-10-08';const row=C.roster(s,'2026-10-08')[0];assert.equal(row.name,'김하늘');assert.equal(row.groupName,'수학반');assert.equal(row.group.id,'a');assert.equal(C.roster(s,'2026-10-09','a',false).length,0);assert.throws(()=>C.mark(s,'s1','2026-10-09','present','',new Date('2026-10-10T10:00:00')));});
test('monthly denominator includes late, excludes excused and unchecked',()=>{let s=fixture();for(const [date,status] of [['2026-10-05','present'],['2026-10-06','late'],['2026-10-07','absent'],['2026-10-08','excused']])s=C.mark(s,'s1',date,status,'',now);const rep=C.report(s,'2026-10');assert.equal(rep.rate,67);assert.equal(rep.totals.excused,1);assert.equal(C.report(s,'2026-09').rate,null);assert.equal(C.report(s,'2026-10','b').records.length,0);});
test('backup roundtrip and rejecting broken or duplicate references',()=>{const s=C.mark(fixture(),'s1','2026-10-08','present','안녕',now);assert.deepEqual(C.parseBackup(C.backup(s)),s);assert.throws(()=>C.parseBackup('{bad'));assert.throws(()=>C.parseBackup(JSON.stringify(s)));const bad=C.clone(s);bad.records.push(C.clone(bad.records[0]));assert.throws(()=>C.validate(bad));bad.records.pop();bad.records[0].studentId='missing';assert.throws(()=>C.validate(bad));const broken=fixture();broken.classes[0].days=[1,1];assert.throws(()=>C.validate(broken));});
test('CSV preserves Korean/newlines/quotes, BOM and neutralizes formulas',()=>{const s=C.mark(fixture(),'s1','2026-10-08','present','줄1\n"줄2"',now);s.records[0].studentName='=HYPERLINK("bad")';const csv=C.csv(s.records);assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes('"\'=HYPERLINK(""bad"")"'));assert.ok(csv.includes('줄1\n""줄2""'));assert.equal(C.csvCell('  @SUM(A1)'), '"\'  @SUM(A1)"');});
test('recorded students still visible on non-scheduled dates',()=>{const s=C.mark(fixture(),'s2','2026-10-08','present','보강',now);assert.equal(C.roster(s,'2026-10-08').length,2);assert.equal(C.roster(s,'2026-10-08','b',true,'박').length,1);});
